### ISSUE TITLE
Source term predictor does not do what it is supposed to

### ISSUE THREAD

**Issue by maxpkatz** [BoxLib-Codes/Castro#18]
The source term predictor adds (dt / 2) * (dS/dt) to the source terms seen by the hydrodynamics. dS/dt is estimated using a backward difference over the last timestep, (S^{n} - S^{n-1}) / (t^{n} - t^{n-1}). However, in the code, the new-time and old-time source terms are actually the corrector and predictor, respectively, not the pure old-time and new-time values of the sources. So the derivative we calculate is not accurate.

**Comment by maxpkatz** [comment]
For the momentum source terms (which are the ones actually used in the hydro, especially after we resolve issue #19), note that S^new = (1/2) S^{n+1} - (1/2) S^{n}, so 2 * S^new = S^{n+1} - S^{n} is actually the numerator of the derivative that we're looking for.

**Comment by zingale** [comment]
but we need to know the dt that was used too -- are you suggesting we compute the dS/dt at the end of the step for use in the next step?

**Comment by maxpkatz** [comment]
That is what we already do. The issue is just that we compute it incorrectly by using (S^{new} - S^{old}) / dt.
