### ISSUE TITLE
write_network.py fails for Python 3.4

### ISSUE THREAD

**Issue by maxpkatz** [BoxLib-Codes/Castro#2]
The following error message is generated when creating the actual_network.f90 file when compiling Castro with Python 3.4:

write_network.py: creating actual_network.f90
write_network.py: working on network file ../../Microphysics/networks/general_null/gammalaw.net...
Traceback (most recent call last):
  File "../../Microphysics/networks/general_null/write_network.py", line 329, in <module>
    write_network(networkTemplate, netFile, outFile)
  File "../../Microphysics/networks/general_null/write_network.py", line 229, in write_network
    fout.write(string.replace(line,"@@NSPEC@@", str(len(speciesList))))
AttributeError: 'module' object has no attribute 'replace'

**Comment by zingale** [comment]
title says write_probin.py, but error is for write_network.py

**Comment by zingale** [comment]
fixed in latest commit
