### ISSUE TITLE
thermal diffusion does not appear to be time-centered properly

### ISSUE THREAD

**Issue by zingale** [BoxLib-Codes/Castro#22]
The function (`Castro::getTempDiffusionTerm`) that calculates the thermal diffusion term, div. sigma grad T, seems to always operate with `S_old`

So it seems that we are never time-centering this term in our source term predictor-corrector update strategy.

Is the solution as simple as changing 

```
   MultiFab& S_old = get_old_data(State_Type);                
```
to 
```
   MultiFab& S_new = get_new_data(State_Type);                
```
for the corrector?

Note that once we compute this term, it looks like we incorporate it into `new_sources` in the correct fashion for the correction.

**Comment by maxpkatz** [comment]
My opinion is that we can just an add is_new flag to that routine, and indeed basically swap out S_new for S_old if the flag is true. Then everything should be time-centered correctly.

**Comment by maxpkatz** [comment]
Note, this also applies to getEnthDiffusionTerm
