### ISSUE TITLE
Inconsistency in application of normalize_species_fluxes

### ISSUE THREAD

**Issue by maxpkatz** [BoxLib-Codes/Castro#4]
In 1D/2D, the call to normalize_species_fluxes in consup is done as the first step, while in 3D, the call is done after the artificial viscosity has been added. This is inconsistent, and also suboptimal for 1D and 2D because the artificial viscosity may cause the species fluxes to no longer be normalized.

**Comment by zingale** [comment]
did you commit fix this?

**Comment by maxpkatz** [comment]
There's a commit in development that fixes this.
