### ISSUE TITLE
ca_initdata is not tiled

### ISSUE THREAD

**Issue by maxpkatz** [BoxLib-Codes/Castro#45]
The call to ca_initdata, which is the user-facing routine intended to be used for the user to fill in the initial state corresponding to their problem setup, is not done with OpenMP. This means that if the user wants to speed up the initialization they need to code in the OpenMP directives by hand. We should make ca_initdata consistent with the rest of the code by threading it at the MFIter level with OpenMP, and tiling it. This should speed up initialization significantly.

We will have to fix the few problem setups that do write in the OpenMP by hand, and we will have to notify users that their ca_initdata implementation needs to be thread-safe and tiling safe (so that, e.g., they should not do something like state(:,:,:,:) = 0.0, and instead only work on the tiling region from lo(:) to hi(:)).

**Comment by WeiqunZhang** [comment]
I consider this as a feature not an issue.  Having ca_initdata inside OMP will put a burden on the user to make sure it is thread safe.  This is not always as simple as it sounds.

**Comment by maxpkatz** [comment]
It is true that sometimes you need to significantly refactor the algorithm to make it thread safe. On the other hand I feel that this is a burden the user has invited onto themselves by choosing to use OpenMP-enabled code. If they are going to do that, then in my view they should be responsible for writing thread-safe code. On the other hand, the drawback is that the user may not even know ca_initdata is in a threaded region, so we would have to clearly warn them about that.

It's worth nothing that the other user-facing routines like prescribe_grav_nd.f90 and ext_src_nd.F90 live in tiled regions, so the user already has the burden on them in those cases.
