### ISSUE TITLE
Introduce NQ to make allocation easier

### ISSUE THREAD

**Issue by zingale** [BoxLib-Codes/Castro#47]
Currently, we dimension the primitive variable vector as:

```
#ifdef RADIATION
   double precision :: q(QRADVAR)
#else 
   double precision :: q(QVAR)
#endif
```

To make life easier, we should introduce new parameters:

* `NQVAR` will always be the pure hydro primitive variables (the primitive version of the `NVAR` state variables)
* `NQRADVAR` will be the radiation components, namely energy density for the groups, `QPTOT` and `QREITOT`
* `NQ` will be used for dimensioning `q`, and will be `NQ = NQVAR + NQRADVAR`

The source term primitive array, `srcQ` will still be dimensioned just as `NQVAR`

**Comment by zingale** [comment]
we need `NQ` in Fortran.  This means that we need to get information from `meth_params_module` and `radhydro_params_module` and then store it somewhere.

All of this might be simpler if we eliminate `radhydro_params_module` completely and put all of the parameters into `meth_params_module`.

**Comment by maxpkatz** [comment]
I advocate eliminating radhydro_params_module.
