### ISSUE TITLE
eliminate LHH.H

### ISSUE THREAD

**Issue by zingale** [BoxLib-Codes/Castro#52]
This header just defines some macros used in interfacing with Fortran that are not standard BoxLib macros.  We should eliminate this header and switch the calls over to the BoxLib conventions. 

This affects radiation only.

**Comment by zingale** [comment]
we should be able to replace the `dimlist()` stuff with `BL_TO_FORTRAN` and `BL_TO_FORTRAN_3D`.

The `Iv` and `Fab` definitions can simply be directly replaced.

**Comment by WeiqunZhang** [comment]
In .cpp files that use `Iv` and `Fab`, one can also do
    using Iv = IntVect;
    using Fab = FArrayBox;

Putting `typedef` or `using` is not a good practice.

**Comment by zingale** [comment]
I'm just going to replace them directly, search and replace

**Comment by WeiqunZhang** [comment]
Then you have to do it manually.

**Comment by zingale** [comment]
The remaining cleanup is for `dimlist()` and is as follows:

For an isolated `dimlist()`, change:

```
dimlist(reg)
```

to 

```
ARLIM(reg.loVect()), ARLIM(reg.hiVect())
```

for the case of a data pointer and bounds, change:

```
exch[exi].dataPtr(), dimlist(xbox)
```

to 

```
BL_TO_FORTRAN(exch[exi])
```

for the prototype, we can then use

```
BL_FORT_FAB_ARG(exch)
```

to receive this
