### ISSUE TITLE
Tolerance used for delta_phi solve

### ISSUE THREAD

**Issue by maxpkatz** [BoxLib-Codes/Castro#60]
In Gravity::solve_for_delta_phi, we have

    Real abs_eps = level_solver_resnorm[crse_level];
    for (int lev = crse_level+1; lev < fine_level; lev++)
        abs_eps = std::max(abs_eps,level_solver_resnorm[lev]);

Why does this only take into account data for levels *below* the fine level? Shouldn't we also consider the residual on the fine_level in addition to everything below it?

**Comment by maxpkatz** [comment]
@WeiqunZhang Could you comment on this? Want to make sure there's not something obvious I'm missing before making this change.

**Comment by WeiqunZhang** [comment]
I don't understand why the fine level is excluded.   Ann does not either.

**Comment by maxpkatz** [comment]
Ok, then if no objections are present, I will make that change.

**Comment by zingale** [comment]
do we want to make this change before merge day?  If it is just changing the loop limits, I can do this.

**Comment by maxpkatz** [comment]
Yes, please.
