### ISSUE TITLE
SDC evolution doesn't update temperature in state upon completion

### ISSUE THREAD

**Issue by zingale** [BoxLib-Codes/Castro#61]
The SDC integration operates directly on the conserved state, and therefore the temperature is not an evolved variable.  At the end of the evolution loop, the temperature is not updated (and in fact, in the plotfiles, it always remains the same as the initial conditions).  This doesn't affect anything except plotting, since T is computed as needed.

**Comment by maxpkatz** [comment]
This should be fixed by commit 862ab80e25d884641557228a972f2e115d7604f6

**Comment by zingale** [comment]
I can confirm this is fixed.
