### ISSUE TITLE
SDC flux registers may not be cleared

### ISSUE THREAD

**Issue by zingale** [BoxLib-Codes/Castro#63]
Comment from @drummerdoc 

> In Castro with SDC, what's the trick to keep the flux registers from being incremented on every SDC iteration? Sorta looks like they get incremented no matter what, which seems wrong.

**Comment by maxpkatz** [comment]
This was addressed by commits ad293c720bbb1cc7ecfddfb0d81ae9c79d2f3790 and 783c6e5a4c5568b7484c19c839c59f7662575d5d. Part of this was recognizing that at the moment, the retry scheme and the SDC iteration scheme are incompatible. This does not seem like it has to be permanent but I did not want to deal with it just yet.
