### ISSUE TITLE
Merge computeTemp for rad and non-rad

### ISSUE THREAD

**Issue by maxpkatz** [BoxLib-Codes/Castro#64]
Radiation has its own logic for computeTemp, this should be merged with Castro::computeTemp. Also, we should clarify if we want the radiation-specific options to live on; if they're not actively used, maybe just consolidate into the existing Castro code.

**Comment by zingale** [comment]
once difference here is that the hydro uses a `growntilebox()` whereas radiation uses a `tilebox`

**Comment by zingale** [comment]
also, the radiation version of `computeTemp` takes 2 arguments, while the hydro version only takes 1.

**Comment by zingale** [comment]
cleanest fix is to just make radiation use the pure hydro methodology
