### ISSUE TITLE
radiation hydro doesn't consider all velocity components in KE

### ISSUE THREAD

**Issue by zingale** [BoxLib-Codes/Castro#66]
In pure hydro, we always compute the kinetic energy as sum of the UMX, UMY, and UMZ components, regardless of dimensionality.  This is because of rotation.

In the rad hydro routines, we are not doing this.

**Comment by zingale** [comment]
this would be addressed naturally as part of issue #70

**Comment by zingale** [comment]
The main place that this seems to be outstanding is in `ca_filt_prim` -- not sure what the purpose of this function is

**Comment by zingale** [comment]
@weiqun, can you give a quick description of why we have the filter primitive variable routine, `filt_prim_?d.f90` in radiation?  What is the use case?

Also, shouldn't the default in 1-d be a no-op like it is in 2- and 3-d?

**Comment by WeiqunZhang** [comment]
There is parameter `Radiation::filter_prim_int` defaulted to 0.  So it will not get called by default.

Filtering primitives at the beginning of `Castro::final_radiation_call` is only implemented in 1d.  It was an experimental feature for shock breakout problem.  But I do not know if it helps.

**Comment by zingale** [comment]
need to update the `ek1` and `ek2` terms in `Castro_advection_1d.F90` too

**Comment by zingale** [comment]
the filter_prim part is now taken care of

**Comment by zingale** [comment]
this is all fixed now (on `radmerge`)
