### ISSUE TITLE
no test suite coverage of radiation do_real_eos = 0

### ISSUE THREAD

**Issue by zingale** [BoxLib-Codes/Castro#68]
We don't have any regression tests with radiation using `do_real_eos = 0`.  Tests that use this approach include:

RadSuOlson
RadSuOlsonMG
RadShestakovBolstad

**Comment by zingale** [comment]
@WeiqunZhang do you have a suggestion of which of these to add to the suite?

**Comment by WeiqunZhang** [comment]
RadShestakovBolstad, RadSuOlson and RadSuOlsonMG.

**Comment by zingale** [comment]
added 2.  RadSuOlsonMG doesn't compile at the moment
