### ISSUE TITLE
move radiation lambda into qaux

### ISSUE THREAD

**Issue by zingale** [BoxLib-Codes/Castro#81]
We can simplify a lot of interfaces if we move the radiation lambda into qaux

**Comment by zingale** [comment]
it looks like the place to do this is in `Castro_hydro.cpp` in the call to `ctoprim`

**Comment by zingale** [comment]
also, I believe it is the case that lamda is never updated in the hydro -- it is computed in the radiation code, so putting it into `qaux` should be fine

**Comment by zingale** [comment]
@WeiqunZhang @maxpkatz any objections to this clean-up?

The idea would be to have `ctoprim` add lambda to `q_aux`, then then we never need to explicitly pass `lam` through the various interfaces, since we will have `q_aux`

**Comment by maxpkatz** [comment]
No objection. Weiqun agreed too.
