### ISSUE TITLE
subroutine problem_checkpoint and problem_restart

### ISSUE THREAD

**Issue by WeiqunZhang** [BoxLib-Codes/Castro#85]
In Source/Problem_F.H, subroutine problem_checkpoint and problem_restart are declared using the BL_FORT_PROC_DECL macro.  But in Exec/hydro_tests/test_convect/Problem_F.H, it's declared as a c function.  The caller in Castro_io.cpp expects the Fortran binding. So Exec/hydro_tests/test_convect/ fails to compile.

Should we change the binding of problem_checkpoint and problem_restart to c everywhere or just change test_convect to Fortran binding?

**Comment by zingale** [comment]
My preference is to make everything `bind(C)`
